---
- name: Clone or Ensure Virtual Machines using pyVmomi
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
  - vars.yml
  - virtual_machines.yml

  tasks:
  - name: Gather Facts of all VMs in Virtual Center or ESXi.
    local_action:
      module: vmware_vm_facts
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
    register: facts

  - name: Check if virtual machine name exists and Verbose UUID
    debug:
        msg: "{{ item.name }}: {{ facts['virtual_machines']['%s'| format(item.name)]['uuid'] }}"
    with_items:
    - "{{ nodes }}"
    ignore_errors: true
    register: uuid

  - name: Generate tasks to clone and create virtual machines
    template:
      src: templates/day1.j2
      dest: './{{ item.name }}.yml'
    with_items:
    - "{{ nodes }}"
    when: uuid|failed

  - name: Generate tasks to ensure the state of virtual machines
    template:
      src: templates/day2.j2
      dest: './{{ item.name }}.yml'
    with_items:
    - "{{ nodes }}"
    when: uuid|succeeded

  - name: Include tasks
    include_tasks: "{{ item.name }}.yml"
    with_items:
    - "{{ nodes }}"

  - name: Gather Facts of all VMs in Virtual Center or ESXi.
    local_action:
      module: vmware_vm_facts
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
    register: facts

  - name: Generate hostvars
    template:
      src: templates/hostvars.j2
      dest: './host_vars/{{ item.name }}.yml'
    with_items:
    - "{{ nodes }}"
  - name: Delete inventory file
    file:
      path: ./inventory
      state: absent
  - name: Remake inventory file
    file:
      path: ./inventory
      state: touch

  - name: Generate inventory file
    lineinfile:
      path: ./inventory
      state: present
      line: "{{ item.name }}"
    with_items:
    - "{{ nodes }}"
